[package]
name = "pnafs"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
clap_complete = "4.5.1"
fuser = "0.14.0"
id_tree = "1.8.0"
libc = "0.2.153"
log = "0.4.21"
pna = "0.7.0"
rpassword = "7.3.1"
simple_logger = { version = "4.3.3" , optional = true }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.28.0", features = ["user"] }

[features]
logging = ["simple_logger"]
