[package]
name = "pna-fs"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
fuser = "0.14.0"
id_tree = "1.8.0"
log = "0.4.20"
pna = "0.6.0"
simple_logger = "4.3.3"
