[package]
name = "pnafs"
version = "0.0.4"
edition = "2021"
authors = ["Portable-Network-Archive Developers"]
repository = "https://github.com/Portable-Network-Archive/fs"
homepage = "https://portable-network-archive.github.io/fs/"
description = "PNA(Portable-Network-Archive) file system"
license = "MIT OR Apache-2.0"
readme = "README.md"
categories = ["filesystem"]
keywords = ["pna", "archive", "cli"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
clap-verbosity-flag = "2.2.2"
clap_complete = "4.5.37"
fuser = "0.15.0"
id_tree = "1.8.0"
libc = "0.2.162"
log = "0.4.22"
memmap2 = "0.9.5"
pna = "0.19.0"
rpassword = "7.3.1"
simple_logger = { version = "5.0.0" , optional = true }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29.0", features = ["user"] }

[features]
logging = ["dep:simple_logger"]

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
