services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: always
    tty: true
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: 'sleep infinity'
