name: format
on:
  pull_request:
  push:
jobs:
  rust_check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-rust
      - name: run check format
        run: cargo fmt --check
        env:
          RUST_BACKTRACE: 1
